---
- name: check, what PECL uploadprogress is installed
  shell: pecl list | grep uploadprogress | wc -l
  register: pecl_uploadprogress_installed

- name: install PECL uploadprogress
  command: pecl install -f uploadprogress
  when: pecl_uploadprogress_installed != 1

- name: add PECL uploadprogress apache php.ini setting
  lineinfile: dest=/etc/php5/apache2/php.ini state=present line="extension=uploadprogress.so"
  notify:
    - Restart apache
